### ISSUE TITLE
Missing Dependency?

### ISSUE THREAD

**Issue by dreadsend** [M-Reimer/wine-lol-glibc#1]
Kinda new to this stuff, but I think Think this is missing bison as a make dependency...

**Comment by M-Reimer** [comment]
This PKGBUILD is based on the official glibc PKGBUILD which also doesn't have a bison dependency.
I just didn't care about separating 64 and 32 bit as wine needs both anyway.
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/glibc
